from PyQt6 import QtWidgets, QtGui, QtCore

class Ui_venprincipal(object):
    def setupUi(self,venPrincipal):
        venPrincipal.setObjectName("venPrincipal")
        venPrincipal.resize(1537, 903)
        venPrincipal.setMinimumSize(110, 25)
        venPrincipal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(venPrincipal.sizePolicy().hasHeightForWidth())
        venPrincipal.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\\\templates\\../img/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        venPrincipal.setWindowIcon(icon)
        #Panel Principal
        self.centralwidget = QtWidgets.QWidget(venPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        venPrincipal.setCentralWidget(self.centralwidget)
        self.panPrincipal.addTab(self.tab, "")
        self.panPrincipal.setObjectName("panPrincipal")
        self.panPrincipal = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panPrincipal.sizePolicy().hasHeightForWidth())
        self.panPrincipal.setSizePolicy(sizePolicy)
        self.panPrincipal.setMinimumSize(QtCore.QSize(0, 768))
        self.panPrincipal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        self.panPrincipal.setFont(font)
        self.panPrincipal.setObjectName("panPrincipal")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        # Pestaña Contactos
        self.pesContactos = QtWidgets.QPushButton(self.centralwidget)
        self.pesContactos.setObjectName("pesContactos")
        self.pesContactos.setText("Contactos") 
        self.pesContactos.setMinimumSize(QtCore.QSize(120, 30))
        self.pesContactos.setMaximumSize(QtCore.QSize(200, 40))
        self.pesContactos.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed,QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        # ID
        self.lblid = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblid.setObjectName("lblid")
        self.lblid.setText("ID")
        self.lblid.setMinimumSize(QtCore.QSize(20, 0))
        self.lblid.setMaximumSize(QtCore.QSize(30, 25))
        self.lblid.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        self.txtid = QtWidgets.QLineEdit(self.centralwidget)
        self.txtid.setObjectName("txtid")
        self.txtid.setMinimumSize(QtCore.QSize(50, 0))
        self.txtid.setMaximumSize(QtCore.QSize(60, 25))
        self.txtid.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)

        # Nombre
        self.lblnombre = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblnombre.setObjectName("lblnombre")
        self.lblnombre.setText("Nombre")
        self.lblnombre.setMinimumSize(QtCore.QSize(45, 0))
        self.lblnombre.setMaximumSize(QtCore.QSize(65, 25))
        self.lblnombre.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        self.txtnombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtnombre.setObjectName("txtnombre")
        self.txtnombre.setMinimumSize(QtCore.QSize(200, 0))
        self.txtnombre.setMaximumSize(QtCore.QSize(250, 25))
        self.txtnombre.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)

        # Notas
        self.lblnotas = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblnotas.setObjectName("lblnotas")
        self.lblnotas.setText("Notas")
        self.lblnotas.setMinimumSize(QtCore.QSize(40, 0))
        self.lblnotas.setMaximumSize(QtCore.QSize(50, 25))
        self.txtnotas = QtWidgets.QLineEdit(self.centralwidget)
        self.txtnotas.setObjectName("txtnotas")
        self.txtnotas.setMinimumSize(QtCore.QSize(140, 0))
        self.txtnotas.setMaximumSize(QtCore.QSize(240, 25))
        self.txtnotas.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)

        # Email
        self.lblemail = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblemail.setObjectName("lblemail")
        self.lblemail.setText("Email")
        self.lblemail.setMinimumSize(QtCore.QSize(45, 0))
        self.lblemail.setMaximumSize(QtCore.QSize(45, 25))
        self.lblemail.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        self.txtemail = QtWidgets.QLineEdit(self.centralwidget)
        self.txtemail.setObjectName("txtemail")
        self.txtemail.setMinimumSize(QtCore.QSize(150, 0))
        self.txtemail.setMaximumSize(QtCore.QSize(240, 25))
        self.txtemail.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)

        # Fecha Alta
        self.lblfechaalta = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblfechaalta.setObjectName("lblfechaalta")
        self.lblfechaalta.setText("Fecha Alta")
        self.lblfechaalta.setMinimumSize(QtCore.QSize(55, 0))
        self.lblfechaalta.setMaximumSize(QtCore.QSize(70, 25))
        self.lblfechaalta.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        self.txtfechaalta = QtWidgets.QLineEdit(self.centralwidget)
        self.txtfechaalta.setObjectName("txtfechaalta")
        self.txtfechaalta.setMinimumSize(QtCore.QSize(50, 0))
        self.txtfechaalta.setMaximumSize(QtCore.QSize(70, 25))
        self.txtfechaalta.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)

        # Móvil
        self.lblmovil = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblmovil.setObjectName("lblmovil")
        self.lblmovil.setText("Móvil")
        self.lblmovil.setMinimumSize(QtCore.QSize(40, 0))
        self.lblmovil.setMaximumSize(QtCore.QSize(50, 25))
        self.lblmovil.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        self.txtmovil = QtWidgets.QLineEdit(self.centralwidget)
        self.txtmovil.setObjectName("txtmovil")
        self.txtmovil.setMinimumSize(QtCore.QSize(60, 0))
        self.txtmovil.setMaximumSize(QtCore.QSize(70, 25))
        self.txtmovil.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)

        # Ciudad
        self.lblciudad = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblciudad.setObjectName("lblciudad")
        self.lblciudad.setText("Ciudad")
        self.lblciudad.setMinimumSize(QtCore.QSize(50, 0))
        self.lblciudad.setMaximumSize(QtCore.QSize(60, 25))
        self.lblciudad.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        self.txtCiudad = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCiudad.setObjectName("txtCiudad")
        self.txtCiudad.setMinimumSize(QtCore.QSize(80, 0))
        self.txtCiudad.setMaximumSize(QtCore.QSize(110, 25))
        self.txtCiudad.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)

        # Ahora añadimos todos los widgets al gridLayout
        self.gridLayout.addWidget(self.lblid, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout.addWidget(self.txtid, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.lblciudad, 0, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout.addWidget(self.txtCiudad, 0, 5, 1, 1)

        self.gridLayout.addWidget(self.lblnombre, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout.addWidget(self.txtnombre, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.lblnotas, 1, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout.addWidget(self.txtnotas, 1, 5, 1, 1)

        self.gridLayout.addWidget(self.lblemail, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout.addWidget(self.txtemail, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.lblfechaalta, 2, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout.addWidget(self.txtfechaalta, 2, 5, 1, 1)

        self.gridLayout.addWidget(self.lblmovil, 3, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout.addWidget(self.txtmovil, 3, 1, 1, 1)
        
        self.verticalLayout.addLayout(self.gridLayout)